name: multiscreen
description: Support multiscreen(different resolution and size of display) for mobile application.
version: 1.3.0
author: Daewook. Kwon<tossy@tossy.me>
homepage: https://github.com/team-tossy/multiscreen

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: me.tossy.flutter.multiscreen
    pluginClass: MultiscreenPlugin
